os:
  - linux

language: php

php:
  - '7.3'
  
addons:
  sonarcloud:
    organization: "zenit"
   
before_script:
  - composer self-update
  - composer install --no-interaction
  - npm install
  
script:
  - vendor/bin/phpunit --coverage-text
  - npm run production
  - sonar-scanner
  
