os:
  - linux

language: php

php:
  - '7.3'
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - npm install
  
script:
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
