os:
  - linux

language: php

php:
  - '7.3'
  
addons:
  sonarcloud:
    organization: "zenit"
    
git:
  depth: false
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - npm install
  
script:
  - npm run production
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner
  
