os:
  - linux

language: php

php:
  - '7.3'
  
addons:
  sonarcloud:
    organization: "zenit"
    token:
      secure: "d4a0zQYY7VGO8Giu1F9EwbCcQ1tFQf9jvKgA1V/CMP8DjsaVbWPnq8/HnRAIiOGuXuAqkp3tHMl0cEkK8GlFWYZSCs9FrE4lqvkBJxt+wQpe/DwyrlI6oAyJIW8AohgNsH+Ea+bPjGauQ5kVkqHuZHcPj9TG7ghL7J4feS8S8mLvqIlFP419bmSvb0GYJirGinja2Ei8PxpjCu99FVCXjBxl+vfC+GeHsnPWo3HPvST+h5kWYVr7aKE4Z90J+FZIc/c8t+TGz45n82j+3jmErXD/uS+rqcH+6sKzFak3q7HJL12sCkdgxziLM7oh7jhFQDE2UwOempa3BR3/J2mQ37gJiVqIUdFlv7JvMuPgg4HFqS5ZI9q0SFXq6IonL9TNXZAZVL+bqXu+gg6XqH6TBC425WzecuMAwj+86ybyf5fWjhWA+GfQ/J3BdzYN58Xmb1+7rRq0TBMJ28tiwOCREy5j2YTsZEp+GlVIiB7BfMH6i4nWml2/2hNicjCDNd2ZNsICzkikaFGiG6bh8dVZfVE06LleoINP5+kQdlOXwgGCD9PAXttYCE2NilxL2lcniAjDCVqqTf8T2G4KeL1fOObKd6qbfAdn0uBbaxhR0iv5nm7uiU1z6ORA2xU/OkuJE9/vWcX3zill2OBgbYbSqYe1WTH4rzXBeD1r8lX/aSs="
      
before_script:
  - composer self-update
  - composer install --no-interaction
  - npm install
  
script:
  - vendor/bin/phpunit --coverage-text
  - npm run production
  - sonar-scanner
  
